/* HOW MANY OFFICIAL LANGUAGES ARE THERE? */
-- SELECT COUNT('language') FROM countrylanguage;

/* WHAT IS THE AVERAGE LIFE EXPECTANCY IN THE WORLD? */
-- SELECT AVG(lifeexpectancy) FROM country;

/* WHAT IS THE AVERAGE POPULATION FOR CITIES IN THE NETHERLANDS? */
-- SELECT AVG(population) FROM city WHERE countrycode = 'NLD';

/* HOW MANY CITIES ARE IN THE DISTRICT OF ZUID-HOLLAND, NOORD-BRABANT AND UTRECHT? */
-- SELECT COUNT(id) FROM city WHERE district IN ('Zuid-Holland', 'Noord-Holland', 'Utrecht');

/* CAN I GET A LIST OF DISTINCT LIFE EXPECTANCY AGES, MAKE SURE THERE ARE NO NULLS */
-- SELECT DISTINCT lifeexpectancy FROM country WHERE lifeexpectancy IS NOT NULL ORDER BY lifeexpectancy;

